project:
  type: website

website:
  title: "ECOS"
  navbar:
    left:
      - about.qmd
      - news.qmd
      - conferences.qmd

format:
  html:
    theme: minty
    css: styles.css
    js: script..js
    toc: true



